title: <p align="center">Dang Van Bao</p>

logo: "/images/picture.png?raw=true"

description: |
  <p align="center">
    <a href="resume.pdf">CV</a> |
    <a href="mailto:dvb22122001@gmail.com">Email</a> |
    <a href="https://www.linkedin.com/in/bao-dang-595773226/">LinkedIn</a> |
    <a href="https://github.com/dvb22122001">GitHub</a>
  </p>

  <p align="justify">
  I am a researcher focusing on machine learning, medical imaging, wearable sensing, and AI-driven healthcare systems.
  <br><br>
  As a Graduate Research Assistant at the University of Montana, my research focuses on post-stroke rehabilitation systems. Specifically, I am developing a wearable ear device designed to monitor and evaluate facial muscle activity to assist in patient recovery
  </p>

show_downloads: false
theme: jekyll-theme-minimal
