title: "Dang Van Bao - Research Assitant"

logo: "/images/projects/picture.jpg"

description: |

  <p align="center" class="typewriter">
    <a href="resume.pdf">CV</a>
    <a href="mailto:dvb22122001@gmail.com">Email</a>
    <a href="https://www.linkedin.com/in/bao-dang-595773226/">LinkedIn</a>
    <a href="https://github.com/dvbao">GitHub</a>
  </p>

  <p class="typewriter">
    Build practical AI systems for healthcare.
  </p>

  <p class="typewriter">
    My current work explores post-stroke rehabilitation through a wearable ear device designed to monitor and evaluate facial muscle activity for patient recovery.
  </p>

show_downloads: false
theme: jekyll-theme-minimal
